### ISSUE TITLE
Broken with dayjs 1.10?

### ISSUE THREAD

**Issue by samuelhalff** [ant-design/antd-dayjs-webpack-plugin#52]
Unless I'm missing something, antd-dayjs-webpack-plugin does not seem to work with the latest version of dayjs (1.10, just released).

I get:

```
init-dayjs.js:1 Uncaught TypeError: dayjs.extend is not a function
    at Object../node_modules/antd-dayjs-webpack-plugin/src/init-dayjs.js (init-dayjs.js:1)
    at __webpack_require__ (bootstrap:853)
    at fn (bootstrap:150)
    at Object.1 (main.ketl.js:11200)
    at __webpack_require__ (bootstrap:853)
    at checkDeferredModules (bootstrap:45)
    at bootstrap:993
    at bootstrap:993
```

**Comment by Orgil** [comment]
same as #51

**Comment by iamkun** [comment]
Duplicate of #51
